### ISSUE TITLE
Technology labels going out of the card

### ISSUE THREAD

**Issue by prem315** [Leapcode-Open/leapcode-frontend#18]
Related project cards 
When there are more technology labels, those labels are going outside of the card. 

<img width="1792" alt="Screenshot 2021-01-03 at 10 08 18 PM" src="https://user-images.githubusercontent.com/8848429/103483865-3759b000-4e10-11eb-889d-40e27ed18ce6.png">

**Comment by ajai-sandy** [comment]
Hi @stanly-johnson I can fix this issue for you, kindly assign this bug under my name and let me know the details to run your application.

**Comment by stanly-johnson** [comment]
Thanks @ajai-sandy! 
@atulsuresh Can you pls help here :)

**Comment by prem315** [comment]
@stanly-johnson @atulsuresh I tried to install the project locally but firebase gives me apiKey, authDomain, projectid, storageBucket, messagingSenderId, appId, measurementId only. Not databaseid

can someone please update the CONTRIBUTING.md with a detailed explanation on how to run the project locally?

**Comment by atulsuresh** [comment]
@prem315 Sorry for the bad documentation we have. Unfortunately, our backend code is not open-sourced yet, which makes setting up on local a bit challenging. 

But we could solve this issue without running on local. 

You might just add a class "flex-wrap" on the parent div where the list is there. 

Let me know if you want help in finding the right file on the code.

**Comment by ajai-sandy** [comment]
@atulsuresh @stanly-johnson Created a PR for the above mentioned issue https://github.com/Leapcode-Open/leapcode-frontend/pull/22, kindly review them.
