### ISSUE TITLE
Modal component is not proper

### ISSUE THREAD

**Issue by prem315** [Leapcode-Open/leapcode-frontend#19]
Modal component is not proper. and it should not have a horizontal and vertical scrollbar.

<img width="1792" alt="Screenshot 2021-01-03 at 2 08 06 PM" src="https://user-images.githubusercontent.com/8848429/103556712-2f654300-4ed8-11eb-9a7b-f756fd9f7781.png">

**Comment by lavanaythakral** [comment]
I'd like to work on this!

**Comment by lavanaythakral** [comment]
Hi, I am unable to run this on localhost. I have seen #21. Could you guide me on how to navigate the code till that gets fixed or if there's a workaround? 
Thanks :)

**Comment by yurywektorovich** [comment]
I'd like to tackle this issue, but I'm stuck on sending invite code to API that does not exist `REACT_APP_APIURL=http://localhost:5000/api`
Where should I send it to verify myself?

**Comment by danmolloy** [comment]
Hi, has this issue been resolved? If not could I please tackle it?

**Comment by priiyaanjaalii0611** [comment]
Hi @stanly-johnson I am new to open source and I want to try fixing this issue I can fix this issue for you, kindly assign this bug under my name
